# Generated by Django 4.2.6 on 2023-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delete_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
